### ISSUE TITLE
Filter is not working

### ISSUE THREAD

**Issue by suseela22** [P3-Core-Dev-Team/P3-Q-A#25]
1. Filter is not working as expected. 
2. Advance filter is also not working. It is fetching the result but throwing some error. Attached the screenshot

Screenshot 1:
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/55573058/05722338-a71b-4bc1-a6ea-bbfd4f745417)

Screenshot 2:
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/55573058/cf122555-3812-4c1c-b4ab-5074fc4c7525)

Screenshot 3:
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/55573058/cfdc7c6b-7d3a-4613-8fb0-26a1090149f8)

**Comment by kilam005** [comment]
Screen shot 2 issue is invalid.
Screen shot 3 issue will be checked

**Comment by suseela22** [comment]
@kilam005 May I know the reason why screenshot 2 is invalid?
The value from the search result is used in filter to search but it is showing empty result.

**Comment by kilam005** [comment]
There is space in front. So the data is trying to look for "          RFL"

**Comment by suseela22** [comment]
Without space also it is not working

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/55573058/73a69c86-3c57-4776-bc05-32d9bb0e30c7)

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/55573058/0322eef8-3857-42f4-b078-c052cb0b7414)

**Comment by kilam005** [comment]
will check and get back on this.

**Comment by kilam005** [comment]
@suseela22 
The issue in screen shot 2 has been verified and acknowledge to exist. It is a valid defect. 

We were unable to create a similar issue in our dev or test environment, so we need you help.
Kindly share the metadata and the associated data, to help us debug.

Please zip and attach the files in this issue.

**Comment by suseela22** [comment]
Attaching the file for reference.

[Reports-Data.zip](https://github.com/P3-Core-Dev-Team/P3-Q-A/files/13114551/Reports-Data.zip)

**Note:**  This issue is occurring when filtering is enabled for multiple columns. This is tested in the version 3.1.7_RC-19102023.

**Comment by sowndaryameiyazhagan** [comment]
@suseela22  this issue occured because of datatype mismatch , we already have similar issue like this 
(issuse-link - https://github.com/P3-Core-Dev-Team/ADS_BE/issues/1482  ) we have  fixed this issue , it will be resolved in  (V_3.1.8) release

**Comment by suseela22** [comment]
@sowndaryameiyazhagan I don't have access for the link u shared. @kilam005 Could you please give access to the folder

**Comment by suseela22** [comment]
Additionally for foreign characters column, the filter is not working as expected. Filter should work as like operation and search for the whole word.

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/55573058/68dac34d-895b-40f6-a7f9-82a5a08ee3c6)

**Comment by sowndaryameiyazhagan** [comment]
Enhancement : added warning symbol in UI if data type is mismatched and disabled the filter option for that mismatched column, the same handled in BE by throwing exception

![Image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/83161895/63d9b69b-6b3e-47a0-8567-5e2193932d31)
![Image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/83161895/c9e7dd2d-16c0-4eac-bfb8-2409fe18dbdf)
![Image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/83161895/3b9db634-5784-4206-80ad-781d42dc197c)

**Comment by Udhayanila8** [comment]
Filter working properly. Tested in 146 server.

![Image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/f00ad779-b32c-4882-a6e1-3888e6f0e84a)

Datatype mismatched warning occurs.

![Image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/9e47a449-d9f4-46be-980d-6d904654305a)

**Comment by Udhayanila8** [comment]
Filter applied for the multiple columns, 44 columns are selected then apply basic filter, the filter option working fine.
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/20fdab7b-de67-4650-bb0b-2daaff3cd8ff)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/7407f973-db46-48e1-acd1-48567fba2985)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/36a47a07-748b-40b9-b24b-b31cb8178faf)

**Comment by kilam005** [comment]
@suseela22 
I believe the region used by implemtation team is upgraded with 2024.01.x version.
Please check and provide closure.

**Comment by suseela22** [comment]
Filter is not working for the encrypted column if it is decrypted. It only works if it remains as encrypted value.

**Encrypted Result filter**
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/55573058/f4662d6d-c26b-4456-8b07-f1e4e863f425)

**Decrypted Result**
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/55573058/bd94e3c8-619b-4c21-aacc-f8759209c3cc)

**Decrypted Result Filter**
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/55573058/1b78c1dd-e34f-472a-9192-7365069bc4c5)

**Comment by kilam005** [comment]
This issue has not be activity worked on currently. Will be taking it shortly once free from any development.

**Comment by ElakkiyaBalasubramanian10** [comment]
Development started by @ClementJosh21 and his team.

**Comment by ClementJosh21** [comment]
@ElakkiyaBalasubramanian10 Implementation is going on.

**Comment by kilam005** [comment]
Development is in progress. Planned to roll out for testing by EOW.

**Comment by kilam005** [comment]
Development was done and demo was provided. Issues to be additionally addressed were informed and expected to be turned around by EOW

**Comment by kilam005** [comment]
@Udhayanila8 please strart testing this out.

**Comment by Udhayanila8** [comment]
Global filter for encrypted columns
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/44c36129-c41a-491f-b80c-257e5fa4736c)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/3d83b267-1900-46c6-b7c8-5871af526f52)
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/faf8dc8a-72d8-476a-9a44-4342ddfe5ee8)
Decrypt the values
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/4107d39c-344b-48fd-bcd9-fcba756b39d6)
After enabling decrypt the page is loading for a long time.
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/6a46d3d7-0267-4464-ab49-4def30a3c7a2)
Also, While clicking view data in the background search job it loads only,
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/b5f919f1-241b-4535-8355-39320f65805e)
Decrypt not applied properly, hence reopen this issue.

**Comment by maheswarareddyi** [comment]
Fix is under development

**Comment by kilam005** [comment]
Fix was demoed to @ClementJosh21 and corrections were suggested. Awaiting fixes from @dinesh-p3.

**Comment by kilam005** [comment]
@dinesh-p3 please provide updates on this asap.
@ashoksri0 make sure the Fix details are tracked properly.

**Comment by kilam005** [comment]
Delivery has been posponted from the planned date. 
internal Demo to be conducted before passing to testing.
If internal demo is ok it will be handed over for testing along with today's deployment.

**Comment by dinesh-p3** [comment]
`RCA`
The encrypted column sorting and filters were not handled

##
`Fix Provided`

The required changes were added to handle the filter & sorting for encrypted columns

**Comment by kilam005** [comment]
In PR review and expected to get merged by EOD by @ClementJosh21 and @selvakumarchandran.

**Comment by maheswarareddyi** [comment]
@Udhayanila8 Please verify and update the fix status

**Comment by Udhayanila8** [comment]
**_Server: 192.168.56.146
Version: 2024.10.45564_RC4_**

Still, issue persists, hence reopening this issue.
Global filter for encrypted columns
![image](https://github.com/user-attachments/assets/9b4838d7-0697-4aea-84bd-231ac198c164)
![image](https://github.com/user-attachments/assets/d133dbe5-91b6-4dfc-b282-349362f9633d)
![image](https://github.com/user-attachments/assets/78316831-f838-4758-ad1b-9aff56b3ec4c)
Select the decrypt option for the encrypted column
![image](https://github.com/user-attachments/assets/3d418fc0-3c32-4c21-8972-1db818ad5ee9)
After selecting the decrypt option and performing a search page loads for a long time, background search still timing runs once the maximum timeout is reached,
![image](https://github.com/user-attachments/assets/4e395540-727a-43ef-a560-41da60041fca)
Manually triggered the background job, but the job has been in-progress for a long for only 640 records
![image](https://github.com/user-attachments/assets/5cb0c48b-705f-4f4d-b728-b4640e965a33)

**Comment by maheswarareddyi** [comment]
@dinesh-p3 @ashoksri0 can you provide the status of this issue fix.

**Comment by dinesh-p3** [comment]
@maheswarareddyi  The fix has already been provided, and it is currently working as expected, please find the screenshots for reference

![bg_job](https://github.com/user-attachments/assets/ade84772-96b4-4210-bf47-cd47554f7e6a)
![bg_search](https://github.com/user-attachments/assets/0d65cf5e-580f-484e-bb57-9e78bbebfccc)
![result](https://github.com/user-attachments/assets/944e1ec0-ff76-4d4a-9fcd-d8979945f716)
![search_info](https://github.com/user-attachments/assets/b1da5f22-02af-400e-97c6-baa4707903ba)
![image](https://github.com/user-attachments/assets/14165267-512d-456b-b199-8c2be81c04ac)

**Comment by dinesh-p3** [comment]
@Udhayanila8 The background search is getting completed, and the sorting & filtering are also working as expected, hence moving this to PRT
![image](https://github.com/user-attachments/assets/285aac2b-79f6-4887-a11b-bd1ec141dc7e)
![image](https://github.com/user-attachments/assets/cd8e0cc3-8952-483f-a810-5a81470609eb)
![image](https://github.com/user-attachments/assets/3c327c0f-9147-42bf-a9ff-348a69a7acdd)

**Comment by kilam005** [comment]
@Udhayanila8 please test and confirm the fixes

**Comment by Udhayanila8** [comment]
**_Server: 192.168.56.146
Version: 2024.10.45564_RC6_**

Get the encrypted filter results within sec, but after selecting decrypt, BG search name change is loading for a long time.
Also in BG search results came after 5 mins.

**_For the 640 records, the decryption time is around 6 mins._**

Global filter for encrypted values
![image](https://github.com/user-attachments/assets/e7232a8d-c7bb-4e42-b0df-319b523476cd)
Enable decrypting in the search area
![image](https://github.com/user-attachments/assets/8ffd6d05-f300-4b3d-9989-3cfe04bb10ba)
Performing the search after decrypt
![image](https://github.com/user-attachments/assets/50d82b7c-325f-4298-ae86-c18b4b73e644)
More than 30 sec it is asking BG search so triggered BG search
![image](https://github.com/user-attachments/assets/068be072-7cf2-4e88-92c8-d6bf51a68b7c)
![image](https://github.com/user-attachments/assets/65c38e82-348b-4e26-ae69-d68133a95f79)
Loading long time while changing the BG search name
![image](https://github.com/user-attachments/assets/0c663a13-232c-41f1-9b9e-af4ebddeba1f)
After a long time able to trigger the BG search
![image](https://github.com/user-attachments/assets/c71b7827-71bf-4a95-99a9-a0dec325b588)
Results came around 6 mins.
![image](https://github.com/user-attachments/assets/5254bc46-d3ae-4b92-8c7b-4b3f54fcb43d)
After decrypting, performing the global filter option
![image](https://github.com/user-attachments/assets/b6c71b4d-8caa-45f6-b4d1-d736c5e3dd71)
![image](https://github.com/user-attachments/assets/b93f9cea-21bf-45e7-9afe-4646b994b5ee)

**Comment by dinesh-p3** [comment]
@Udhayanila8 
The search without decryption will be quick, as no decryption is involved. However, the decrypted search will take more time because each record will need to be decrypted, followed by data type validation on the decrypted data to ensure it matches the expected result column type, This validation is performed to restrict filtering and sorting for columns with data type mismatches

**Comment by dinesh-p3** [comment]
@Udhayanila8 
The BG search name validation is working as expected. I can assign a new name to the BG search and schedule it. The loading time you experienced may have been due to high demand on the server from multiple concurrent processes. Please check again, and let us know if you encounter any issues. 
https://github.com/user-attachments/assets/e2c10959-8625-4d16-9576-7240aec48463

**Comment by ashoksri0** [comment]
@Udhayanila8  what was the current status for this issue?

**Comment by kilam005** [comment]
@ClementJosh21 and myself have identifed some bottlenecks in teh code and improvization is in progress.
Will check and update once the fixes are in place.

**Comment by ClementJosh21** [comment]
The PR is merged and the issue is forwarded to the testing team.

`PR link` : [3570](https://github.com/P3-Core-Dev-Team/ADS_BE/pull/3570)

**Comment by Srividhya2506** [comment]
http://192.168.56.146:4081/
2024.10.45564_RC9

Created a Advanced search with encrypted columns, performed sort and filter for encrypted columns then enabled decrypt and updated. Scheduled background job with job name, Job got completed and can able to view data and performed sort and filter for decrypted columns. It is working as expected in 146 server.

Encrypted data
![image](https://github.com/user-attachments/assets/c0456f8a-f4bf-4439-a270-63e9608c6ee7)
Encrypted sorting
![image](https://github.com/user-attachments/assets/76feb79f-8a74-4858-9916-ac7789868d58)
![image](https://github.com/user-attachments/assets/4b2cbc59-0afe-4936-af6e-f4b7fa2712c5)
Encrypted global filter
![image](https://github.com/user-attachments/assets/39206c1c-83df-46df-9f2c-bb2d1fe85075)
Encrypted Advance filter
![image](https://github.com/user-attachments/assets/751cd66b-2505-4ef0-a87b-71243f3d84d1)
Enabling Decrypt
![image](https://github.com/user-attachments/assets/07f00a9a-6643-40f2-bd45-705240ff5c4e)
Scheduled background job
![image](https://github.com/user-attachments/assets/c50f3d0c-707e-4175-9fda-7de88bde7bbc)
![image](https://github.com/user-attachments/assets/7f18c454-bc34-474c-ad07-553f743a5b7f)
decrypted data
![image](https://github.com/user-attachments/assets/e78ade6c-51fc-4e59-8c12-46e823f25638)
Decrypted sorting
![image](https://github.com/user-attachments/assets/c0772adf-2dfd-4129-a466-359c19ac34d7)
![image](https://github.com/user-attachments/assets/1f2aa81c-40e2-45c2-ae28-cbc6a938dd46)
Decrypted filter
![image](https://github.com/user-attachments/assets/66ea688d-e046-4f92-ba2c-a3271904c509)
![image](https://github.com/user-attachments/assets/7e6e5ddc-1a59-4732-82b1-d8e9193cd545)

**Comment by Udhayanila8** [comment]
@suseela22 

This issue is tested and verified in the 146(test - on_prem) server. Also, added the respective screenshots.
This fix is available in the 2025.01.45679 version. This version is deployed at https://uat-ads.platform3solutions.com/
region.
Please verify and update.

**Comment by kilam005** [comment]
@suseela22 
expecting verfiication and closure confirmation.
please complete before 13th March 2025

**Comment by suseela22** [comment]
@Kiruthi23 Verify and close it

**Comment by kilam005** [comment]
@suseela22  / @Kiruthi23 
Please check and give closure.
This is waiting for verification for about 2 weeks now.

This issue will be auto closed based on testing comments if no action is not confirmed by 13th mar eod

**Comment by Kiruthi23** [comment]
The issue persists in the Advanced Filter for the **IN** and **NOT IN** operators.

Currently, multiple values (comma-separated) cannot be provided when selecting the **IN/NOT IN** operator.

Results Screenshot:

![Image](https://github.com/user-attachments/assets/dd9d6ac0-56fb-44a0-9dcc-5dfabdbd4611)

Issue Screenshot:

![Image](https://github.com/user-attachments/assets/36570824-a7cf-4635-8989-6da916eda161)

![Image](https://github.com/user-attachments/assets/c50cc69f-ab65-4f6d-a258-91ae134f0d2f)

**Comment by Thilak-Saravanan** [comment]
@Kiruthi23 

The initial issue related to filters not working on encrypted fields has been resolved.

We acknowledge the issue with the IN and NOT IN operators in the advanced filter. However, since this deviates from the original issue, please log a separate ticket for it and close the initial issue if it is working as expected.

**Comment by Kiruthi23** [comment]
Additionally, Filter on the Decrypted Data Column (Column Data Type: String) is not working as expected for operators (=, !=, in & not in).

**Search Result Configuration:**

![Image](https://github.com/user-attachments/assets/7e15f2d9-2039-4691-9ee8-b868dd989d87)

**Search Results:**

![Image](https://github.com/user-attachments/assets/8ef07006-99df-4a47-8d8a-1e035e3cb210)

**Filter using EQUALS_TO (=) Operator:**

![Image](https://github.com/user-attachments/assets/76a00da5-0d4c-42ea-9f89-22b96fd3b523)

**Filter using NOT_EQUAL_TO (!=) Operator:**

![Image](https://github.com/user-attachments/assets/adf3ba09-47b7-4da5-8bbd-e36043a740aa)

**Filter using IN Operator:**

![Image](https://github.com/user-attachments/assets/ddaaf359-06b0-4cae-ae08-c25e376ad794)

**Filter using NOT IN Operator:**

![Image](https://github.com/user-attachments/assets/c108bfa5-7da5-40b5-9abe-f5886f6812cf)

**_Additional context:_**
Build no : 2025.01.45679
Region : Platform 3 Solutions - Sandbox
Client : ADS UAT Environment

**Comment by dinesh-p3** [comment]
@maheswarareddyi 

Please find below the cases that need to be handled:

**Case 1: Sorting/Filtering with Masked Columns**

When sorting or filtering, if a column is masked, how should the sorting and filtering functionality behave? We need to clarify the expected behavior in this scenario.

**Case 2: Advanced Filter with 'IN' Operator**

Currently, we are separating multiple values with a comma. However, if a value itself contains a comma, this approach will not work as expected. To resolve this issue, we could request that the user enclose each value in single quotes.

For example:
'value1', 'value with, comma', 'value without comma'

Please provide your comments and expectations for the above cases.

**Comment by dinesh-p3** [comment]
@Kiruthi23 

The extracted data contains, an invalid data format, please find the screenshots,

Working case:

![Image](https://github.com/user-attachments/assets/0f096f55-635b-4e2f-b33b-fc493d7d375d)

![Image](https://github.com/user-attachments/assets/caff2807-f8f8-44af-9df7-18baadf367d4)

Failure case:

![Image](https://github.com/user-attachments/assets/ac878468-68a4-4656-a2d0-a8b204d472ee)

Data set:

![Image](https://github.com/user-attachments/assets/fb51ddcf-dfcb-4cb5-9980-7b4f69c53761)

Paraquat:

![Image](https://github.com/user-attachments/assets/d17fb026-81d0-4741-9ab8-67645acdad71)

![Image](https://github.com/user-attachments/assets/14b09534-d00e-41e5-93ec-999d3c582edf)

Data in OpenSearch:

![Image](https://github.com/user-attachments/assets/03b0d73c-701e-408d-9c3d-f30fdf53deb1)

**Comment by dinesh-p3** [comment]
@suseela22 / @Surinarayanan 

Can we create separate enhancement/feature request tickets for the case mentioned below to track them separately?

> [@maheswarareddyi](https://github.com/maheswarareddyi)
> 
> Please find below the cases that need to be handled:
> 
> **Case 1: Sorting/Filtering with Masked Columns**
> 
> When sorting or filtering, if a column is masked, how should the sorting and filtering functionality behave? We need to clarify the expected behavior in this scenario.
> 
> **Case 2: Advanced Filter with 'IN' Operator**
> 
> Currently, we are separating multiple values with a comma. However, if a value itself contains a comma, this approach will not work as expected. To resolve this issue, we could request that the user enclose each value in single quotes.
> 
> For example: 'value1', 'value with, comma', 'value without comma'
> 
> Please provide your comments and expectations for the above cases.

**Comment by Srividhya2506** [comment]
http://192.168.56.146:4081/
2025.03.45728_RC08

Not Working as expected so reopening this issue.

* As per the expectation the sorting and filtering must be applicable for only unmasked values. But can able to perform sorting for masked values which is not the expected behaviour. So it is not working as expected.

* IN and NOT IN operator not working as expected. For IN operator It is displaying 'no data available', If a value contains commas, escape characters, or special characters which is enclosed in single quotes to treat as a single value. But It is not working when the value is given in single quotes.
  For NOT IN if the value in given in single quotes it is not filtering properly.

* The info message for IN and NOT IN operator is not available in screen.

Data for reference:

![Image](https://github.com/user-attachments/assets/d3c42581-359e-436e-a2b8-1dc98c35f7e4)

Screenshots:
Sort in mask field:

![Image](https://github.com/user-attachments/assets/84674932-1b9c-4cf4-943a-128da1409a14)

IN operator

![Image](https://github.com/user-attachments/assets/63e82197-8e09-408e-9290-6862d1910e20)

NOT IN operator

![Image](https://github.com/user-attachments/assets/90e4db41-8fe4-42c4-94e4-6840f18f3957)

No Info message:

![Image](https://github.com/user-attachments/assets/9e6e82bb-1b1d-4b64-ba03-da1ffb8d2a9e)

**Comment by Surinarayanan** [comment]
Revalidating the scenarios in the latest build.

**Comment by Surinarayanan** [comment]
**RCA:**
Unable to provide more than value in the filter condition.

**Fix:**
Enable an option to give multiple values in IN and Not IN conditions with a comma separator.

**Comment by Srividhya2506** [comment]
https://client-region-test.platform3solutions.com/
2025.03.45728_P2

@Lavanya-SP Okay thanks for the info.

Filter and Sorting for IN and NOT IN operators by wrapping the value in single quotes is working as expected and other sort and filter also working fine. And for mask field sort and filter option is disabled and it is working as expected.

 
But "Index not found" issue it is raised as a new ticket https://github.com/P3-Core-Dev-Team/ADS_BE/issues/4256 and enhancement for using \ (Slash) is also raised as a new ticket https://github.com/P3-Core-Dev-Team/ADS_BE/issues/4255. Will give verified status once these two tickets are closed from our end.

Working Screenshots:

IN and NOT IN Operator
![Image](https://github.com/user-attachments/assets/6e997466-b77d-4056-a0eb-ec10b9b922c4)

![Image](https://github.com/user-attachments/assets/3bfdf2cb-5f9d-4dbc-aa2a-27747e636431)

![Image](https://github.com/user-attachments/assets/0e3c8882-a2ca-4c1c-9d26-b01b0f3d324c)

![Image](https://github.com/user-attachments/assets/e32eec5a-c35a-4a44-b327-5deb8685c961)

![Image](https://github.com/user-attachments/assets/c5b4697f-b089-4ae8-9f0f-c587cfa5fdda)

![Image](https://github.com/user-attachments/assets/8e39bd8b-8a9d-4df0-92b0-5cd5ee4909bc)


Masked field
![Image](https://github.com/user-attachments/assets/de6f69a5-15c3-4736-9325-40bd35df71bc)

![Image](https://github.com/user-attachments/assets/c693d1e6-1e05-4bcd-8182-e1dea23a81eb)

Advance search

![Image](https://github.com/user-attachments/assets/3fe55e21-c980-4d07-943a-eeecea1037c9)

![Image](https://github.com/user-attachments/assets/5c895d83-4e68-4924-850e-ea473aae475c)

![Image](https://github.com/user-attachments/assets/b10f7275-9c11-4f85-87ee-23e1ba33e0ca)

![Image](https://github.com/user-attachments/assets/9e409722-b35f-48d0-9b22-cb4363586714)

![Image](https://github.com/user-attachments/assets/af060bf1-d855-41cb-b2e9-f6da3969827d)

Encrypted value filter

![Image](https://github.com/user-attachments/assets/b0d9ac72-a6b6-43ec-8cf6-1d76746d63fb)

![Image](https://github.com/user-attachments/assets/c2fd5d61-39d3-45f3-8493-e8728583f13b)

![Image](https://github.com/user-attachments/assets/c4af8246-fa94-430c-bda1-c129a854d886)

Decrypted Value filter

![Image](https://github.com/user-attachments/assets/d963cf0b-30e8-4fc7-8c1d-3982de233a86)

![Image](https://github.com/user-attachments/assets/021abae2-2861-4c4e-ac84-a7fbdc66e240)

![Image](https://github.com/user-attachments/assets/5227f678-c34a-4eb9-b358-8805c7366ead)

![Image](https://github.com/user-attachments/assets/50681a28-1b1b-4c71-8238-22b0faf0f587)

Other filters

![Image](https://github.com/user-attachments/assets/2c2edadb-f833-4c31-b4b6-6a0bd3aa347b)

![Image](https://github.com/user-attachments/assets/1e411c14-b73e-4002-837d-3f8f87c8419e)

![Image](https://github.com/user-attachments/assets/c50db9c7-23d2-40da-8474-bd35b830cfac)

![Image](https://github.com/user-attachments/assets/42a1434c-4188-4f1c-867a-445b29f775ca)

![Image](https://github.com/user-attachments/assets/ab24f258-e91e-4f73-9778-d9054b081d25)

![Image](https://github.com/user-attachments/assets/f2860bbf-523d-455c-9c05-6f8d0e833be5)

![Image](https://github.com/user-attachments/assets/7ac8ae3c-4bdb-4c15-b101-c7c8b1848f37)

![Image](https://github.com/user-attachments/assets/bdad4ffd-0976-4775-bf79-a66b7cb8dcfe)

**Comment by Surinarayanan** [comment]
@Srividhya2506 Kindly attached the filter condition test cases in the issue link.

**Comment by Srividhya2506** [comment]
@Surinarayanan, Unable to attach the testcase sheet here so I have sent through mail. If needed please forward to others as well.

**Comment by Srividhya2506** [comment]
https://client-region-test.platform3solutions.com/
2025.03.45728_P4

1 issue https://github.com/P3-Core-Dev-Team/ADS_BE/issues/4256 and 1 enhancement https://github.com/P3-Core-Dev-Team/ADS_BE/issues/4255 has been closed.

In the data if we have both single quotes and slash \ and other special characters, In such case, filter is not working for some data.

![Image](https://github.com/user-attachments/assets/b803f604-0916-451d-9bda-c4ff93d178ba)

![Image](https://github.com/user-attachments/assets/76e7871f-4c15-463e-9dad-dcc3bbd05080)

![Image](https://github.com/user-attachments/assets/f3d83866-ae33-43d0-a99e-ee277a383083)

![Image](https://github.com/user-attachments/assets/13010617-20cf-4aa4-9b7d-0743616f235f)

![Image](https://github.com/user-attachments/assets/0cf87390-2cc6-4387-884d-1d7235ab028d)

**Comment by Srividhya2506** [comment]
https://client-region-test.platform3solutions.com/
2025.03.45728_P6

Filter - IN and NOT IN operator for string dataset which have single quotes and other regex characters by using slash\ the results are fetched properly. And also, by wrapping in single quotes the results are fetched properly. Thus, working as expected.

<img width="1915" height="1028" alt="Image" src="https://github.com/user-attachments/assets/5a97e5a9-c47c-4aa0-b178-12b9856431a8" />

<img width="1918" height="1031" alt="Image" src="https://github.com/user-attachments/assets/d8b16c23-eb3d-4319-9dab-e1a5d09ba0a1" />

[Issue_25.docx](https://github.com/user-attachments/files/21433645/Issue_25.docx)

**Comment by padminiganapathi** [comment]
@suseela22 : The fix is available in ADS 2025.03.45728_P6. Validate and provide closure for the issue.
